version: "3"
services:
  aiohttp:
    build: .
    volumes:
      - ./:/app
    command: gunicorn delivery_pdf.main:init -b :${SERVER_PORT} --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - host
  athena:
    image: arachnysdocker/athenapdf-service:latest
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      - host
networks:
  host: