version: "3"
services:
  aiohttp:
    build: .
    volumes:
      - ./:/app
    command: gunicorn delivery_pdf.main:init -b :8500 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8500:8500"
    networks:
      - host
  athena:
    image: arachnysdocker/athenapdf-service:latest
    ports:
      - "8080:8080"
    networks:
      - host
networks:
  host: